[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#C08A38"
backgroundColor = "#FFFBF0"
secondaryBackgroundColor = "#F5ECD9"
textColor = "#5A4214"
font = "sans serif"

[deprecation]
showfileUploaderEncoding = false

[logger]
level = "info"

[client]
showErrorDetails = true
toolbarMode = "auto" 